login:
  path: /login
  defaults: {_controller: '\Trillium\Controller\Hello', _action: login}
hello:
  path: /{name}
  defaults: {_controller: '\Trillium\Controller\Hello', _action: 'say', name: 'Kilte'}
login.check:
  path: /login/check
  defaults: {_controller: null}
logout:
  path: /logout
  defaults: {_controller: null}